site_name: Inventory Manager Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - User Guide: usage.md
  - System Overview: architecture.md
  - Services: api.md
  - Development: development.md
  - Known Limitations: limitations.md

theme:
  name: material
